### ISSUE TITLE
WS Socket und flot edit

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.ws#20]
Wenn ein WSSocket in der Web Instanz eingetragen ist, funktioniert flot edit nicht mehr.
https://forum.iobroker.net/topic/58534/flot-geht-nicht-mehr-mit-8082-bei-ws-an?_=1664689258326

Lösung nur durch extra Instanz (ohne ws):
https://github.com/ioBroker/ioBroker.ws/issues/14

**Comment by Apollon77** [comment]
Bitte mal neueste Flot Beta versuchen

**Comment by Apollon77** [comment]
... und ws update gabs auch
