### ISSUE TITLE
Socket.IO Java/Android

### ISSUE THREAD

**Issue by Schnup89** [ioBroker/ioBroker.ws#26]
Hello,

for my project (https://github.com/Schnup89/ioBroker_WearV2) I've used the iobroker socket.io adapter and I want to migrate it to the websocket adapter.

I've used socket.io java client (v1.0.1) for android to get the data from socket.io (v2.x) iobroker server.
https://socketio.github.io/socket.io-client-java/installation.html

This adapter is installed and running on port 8085, but with the socket.io client v1.0.1 or v2.0.1 I always get "parse error".
Should it be possible with socket.io library out of the box or is there any modification necessary?

**Comment by Apollon77** [comment]
In fact for socket.io pöease use the socket.io adapter :-) Pure ebsockets are more simple and you simply connect using anwebsocket and NOT socket.io. (For your info: socket.io is using websockets but also having long polling fallbacks and such things and these are NOT existent on "pure websocket adapter"

**Comment by Schnup89** [comment]
Thank you for your fast answer.

Let me ask two more questions:
I have some trouble getting SocketIO (v1.01) working stable/reliable on android and I'm currently reworking the code so would you advice to change to this websockets adapter?
If yes, is there any documentation which url has to be requested?
http://iobroker.lan:8084/ always gives me "Not Implemented"
With socket.io on Port 8085 it respond on http://iobroker.lan:8085/socket.io/

**Comment by Schnup89** [comment]
> but in fact socket.io 1 is veeery old and outdated!

That's exaclty my problem, Socket.IO Java Client v1 is outdated and Socket.IO Java Client v2 is only compatible with Socket.IO Server 3.x and 4.x which is not provied by the iobroker socket.io adapter.

Because of this I would rewrite my code to use this (the iobroker websockets adapter) but I don't know how start/call the websockets api

**Comment by Apollon77** [comment]
But then the 1.x client should work with the 2.x server in the adapter ... whats exactly the issues?

**Comment by Schnup89** [comment]
Since 1.x Client is outdated and I can not use the 2.x Client with the "ioBroker Socket.IO-Adapter" or "ioBroker WS-Adapter" I would like to know how I can make http request (over websockets) to get data from through this adapter

**Comment by Apollon77** [comment]
In fact use a websocket client and connect against the port of the ws adapter with kind of ws://ip:port ... there should be nothing more needed. There is a javscript browser example in https://github.com/ioBroker/ioBroker.ws/blob/main/example/conn.js#L259

**Comment by Schnup89** [comment]
Thanks you! First connection was successfull, I hope the connection is more stable with the native websockets.
