### ISSUE TITLE
No connect with Pixel Watch

### ISSUE THREAD

**Issue by coyote9999** [ioBroker/ioBroker.ws#28]
Habe die APK über ADB installiert.
Den Websocket Adapter auf Port 8084 eingestellt.

Grüner Haken in der Watch App wechselt ständig vom roten X zum grünen Haken.
Protokoll des ioBrokers läuft voll. (s. Screenshot)

Aktuelle ioBroker Installation auf VM.
Hatte jemand diesen Fehler schonmal?

LG

![2023-02-04 20_05_54-logs - ioBrokerVM](https://user-images.githubusercontent.com/15721437/216785273-cb93b691-f572-4392-b831-3d7b79041eec.png)

**Comment by Apollon77** [comment]
Welche Watch App ist gemeint? Die meldung im log heosst das sich jemand verbindet und wieder disconnedted ... also in sofrt alles ok ... Was ist das Problem? Wenn das Log stört dann bitte Loglebel erhöhen auf "warn"

**Comment by coyote9999** [comment]
Hallo!

Es geht um die Watch App ioBroker_WearV2 (https://github.com/Schnup89/ioBroker_WearV2)
Das Problem scheint eher dort gelagert zu sein.

Habe das Problem dem Entwickler gemeldet.

**Comment by coyote9999** [comment]
Das Problem wurde vom Watch App Entwickler gelöst.
Es ist kein WebSocket Problem.
